name: python test

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: My action
        id: my_action
        uses: parkhs21/git_action@main
        with:
          openai-token: ${{ secrets.OPENAI_TOKEN }}
